version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASS: fathytest
      MYSQL_PORT: 3306
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fathytest
      MYSQL_DATABASE: internship
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: